"""Specialized facade editing for exact rectangular house-box versions."""

from __future__ import annotations

import uuid
from typing import Literal

import sqlalchemy as sa
from fastapi import APIRouter, status
from pydantic import BaseModel, Field, TypeAdapter, ValidationError
from sqlalchemy.orm import Session

from app.api.deps import DbDep, IdempotencyKey, PrincipalDep
from app.api.errors import ValidationFailedError
from app.api.schemas import JobAccepted
from app.engineering.facade import MAX_OPENINGS, FacadeOpening, FacadeRequest
from app.engineering.house_box import HouseBoxRequest
from app.models.core import WorkspaceRole
from app.models.execution import Job, JobStatus
from app.models.versioning import ProjectVersion
from app.services import jobs, projects
from app.services.authz import require_workspace_role
from app.services.house_boxes import HOUSE_BOX_JOB

router = APIRouter(tags=["facades"])
FACADE_ADAPTER = TypeAdapter(FacadeRequest)


class FacadeOpeningBody(BaseModel):
    kind: Literal["window", "door"]
    side: Literal["front", "back", "left", "right"]
    center_mm: float = Field(ge=100, le=49_900)
    width_mm: float = Field(ge=300, le=5_000)
    height_mm: float = Field(ge=300, le=5_000)
    sill_mm: float | None = Field(
        default=None,
        ge=0,
        le=15_000,
        description="Window sill height (default 900). Doors start at floor level: omit or 0.",
    )


class FacadeEditBody(BaseModel):
    wall_thickness_mm: float = Field(default=250, ge=100, le=600)
    roof: Literal["none", "flat", "gable"] = "flat"
    roof_height_mm: float = Field(default=1_200, ge=200, le=5_000)
    overhang_mm: float = Field(default=300, ge=0, le=2_000)
    openings: list[FacadeOpeningBody] = Field(default_factory=list, max_length=MAX_OPENINGS)


FACADE_JOB = "edit_facade"


class IneligibleVersionError(Exception):
    def __init__(self, reason: str, message: str) -> None:
        super().__init__(message)
        self.reason = reason


def _producing_job(db: Session, version: ProjectVersion) -> Job | None:
    """The succeeded server job that wrote this version. Provenance is client-writable through
    the versions API, so only the job row (input validated and enqueued by the server) counts."""
    return db.scalar(
        sa.select(Job)
        .where(
            Job.project_id == version.project_id,
            Job.type.in_((HOUSE_BOX_JOB, FACADE_JOB)),
            Job.status == JobStatus.succeeded,
            Job.result["version_id"].astext == str(version.id),
        )
        .limit(1)
    )


def _rectangular_house(db: Session, version: ProjectVersion) -> HouseBoxRequest:
    """Follow facade edits back to the house-box job and require its validated shape to be
    an exact rectangle; anything else (scans, imports, L/T shapes, forged provenance) fails."""
    seen: set[uuid.UUID] = set()
    current = version
    while current.id not in seen:
        seen.add(current.id)
        job = _producing_job(db, current)
        if job is None:
            raise IneligibleVersionError(
                "not_house_box",
                "the facade editor needs a rectangular house-box version; this version was "
                "not generated by the house-box builder (scanned, imported or hand-made "
                "geometry is not eligible)",
            )
        if job.type == HOUSE_BOX_JOB:
            try:
                house = HouseBoxRequest(**dict(job.input.get("request") or {}))
            except (TypeError, ValueError) as exc:
                raise IneligibleVersionError(
                    "invalid_house_box", f"the source house-box request is invalid: {exc}"
                ) from exc
            if house.shape != "rectangle":
                raise IneligibleVersionError(
                    "not_rectangular",
                    f"the facade editor needs a rectangular house-box version; "
                    f"this house is {house.shape}",
                )
            return house
        source_id = job.input.get("version_id")
        source = db.get(ProjectVersion, uuid.UUID(str(source_id))) if source_id else None
        if (
            source is None
            or source.project_id != current.project_id
            or source.id != current.parent_version_id
        ):
            break
        current = source
    raise IneligibleVersionError(
        "broken_lineage",
        "the facade editor needs a rectangular house-box version; its facade lineage "
        "could not be traced back to one",
    )


@router.post(
    "/models/{version_id}/facade",
    status_code=status.HTTP_202_ACCEPTED,
    response_model=JobAccepted,
)
def edit_facade(
    version_id: uuid.UUID,
    body: FacadeEditBody,
    db: DbDep,
    principal: PrincipalDep,
    idempotency_key: IdempotencyKey = None,
) -> JobAccepted:
    version = projects.get_version(db, user_id=principal.user_id, version_id=version_id)
    project = projects.get_project(db, user_id=principal.user_id, project_id=version.project_id)
    require_workspace_role(db, principal.user_id, project.workspace_id, WorkspaceRole.editor)
    try:
        house = _rectangular_house(db, version)
    except IneligibleVersionError as exc:
        raise ValidationFailedError(
            str(exc), {"version_id": str(version.id), "reason": exc.reason}
        ) from exc
    try:
        request = FacadeRequest(
            length_mm=house.length_mm,
            width_mm=house.width_mm,
            floor_height_mm=house.floor_height_mm,
            floors=house.floors,
            wall_thickness_mm=body.wall_thickness_mm,
            roof=body.roof,
            roof_height_mm=body.roof_height_mm,
            overhang_mm=body.overhang_mm,
            openings=[
                FacadeOpening(**item.model_dump(exclude_none=True)) for item in body.openings
            ],
        )
    except (TypeError, ValueError, ValidationError) as exc:
        raise ValidationFailedError(str(exc)) from exc
    job = jobs.enqueue(
        db,
        workspace_id=project.workspace_id,
        project_id=project.id,
        project_version_id=version.id,
        job_type=FACADE_JOB,
        input={
            "version_id": str(version.id),
            "request": FACADE_ADAPTER.dump_python(request, mode="json"),
        },
        created_by=principal.user_id,
        idempotency_key=idempotency_key,
    )
    return JobAccepted(job_id=job.id, status=job.status, type=job.type)
